version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb://mongodb:27017/contact-manager-app"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
